package app.skerry.ui.terminal

import androidx.compose.ui.input.key.KeyEvent

// True when the key event was generated by the on-screen keyboard (not a physical one), so the
// hidden IME field already delivers its text and the redundant key event can be dropped.
internal expect fun isSoftKeyboardEvent(event: KeyEvent): Boolean
