"""Explicit dispatch profiles; agents never silently inherit the parent's maximum effort."""
import tomllib
import json
from pathlib import Path
from . import capabilities, policy, state


def configuration(cwd=None):
    data = tomllib.loads(Path(state.repo_root(cwd), "tools/harness/agents.toml").read_text())
    for name, profile in data["profiles"].items():
        if not profile.get("model") or profile.get("reasoning_effort") not in ("low", "medium", "high"):
            raise ValueError(f"invalid bounded agent profile: {name}")
    return data


def profile(name, cwd=None, focus=(), ecc_root=None):
    profiles = configuration(cwd)["profiles"]
    if name not in profiles:
        raise ValueError(f"unknown agent profile: {name}")
    selected = capabilities.plan(cwd, focus, ecc_root, role=name)
    return {"role": name, **profiles[name], "fork_turns": "none",
            "capabilities": selected, "capability_instruction": selected["instruction"],
            "context": "Task, files, relevant contracts and review token; no full chat history."}


def plan(cwd=None, focus=(), ecc_root=None):
    config = configuration(cwd)
    parallel = config["limits"]["max_parallel"]
    # Conservative on machines without a portable memory inventory.
    meminfo = Path("/proc/meminfo")
    if not meminfo.exists():
        parallel = 1
    else:
        memory = {line.split(":")[0]: int(line.split()[1]) for line in meminfo.read_text().splitlines()}
        available = memory.get("MemAvailable", 0) / 1024**2
        swap = memory.get("SwapTotal", 0)
        if (available < config["limits"]["minimum_available_gib"] or
                (swap and memory.get("SwapFree", 0) < swap / 4)):
            parallel = 1
    selected = capabilities.plan(cwd, focus, ecc_root)
    for specialist in selected["specialists"]:
        specialist["dispatch"] = profile(specialist["profile"], cwd, focus, ecc_root)
    return {"max_parallel": parallel, "gradle_parallel": 1, "capabilities": selected,
            "reviewers": [profile(name, cwd, focus, ecc_root) for name in policy.reviewers(cwd)],
            "support": [profile(name, cwd, focus, ecc_root) for name in ("explorer", "worker")]}


def sync_configs(cwd=None):
    root = Path(state.repo_root(cwd))
    target = root / ".codex/agents"
    target.mkdir(parents=True, exist_ok=True)
    files = []
    for name in ("skerry-reviewer", "skerry-kotlin-reviewer", "skerry-security-reviewer"):
        selected = profile(name, cwd)
        prompt = (root / f".agents/reviewers/{name}.md").read_text() + "\n\n" + capabilities.INSTRUCTION
        values = {"name": name, "description": selected["purpose"], "model": selected["model"],
                  "model_reasoning_effort": selected["reasoning_effort"], "developer_instructions": prompt}
        file = target / f"{name}.toml"
        file.write_text("# Generated by gate.py sync-agents; edit the portable prompt/profile.\n" +
                        "\n".join(f"{key} = {json.dumps(value, ensure_ascii=False)}" for key, value in values.items()) + "\n")
        files.append(str(file))
    return files
