#!/usr/bin/env python3
"""Generates UnicodeWidthTables.kt — the column-width tables the terminal grid measures with.

    curl -sSfLO https://www.unicode.org/Public/16.0.0/ucd/EastAsianWidth.txt
    curl -sSfLO https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedGeneralCategory.txt
    tools/unicode/gen_width_tables.py EastAsianWidth.txt DerivedGeneralCategory.txt 16.0.0

Wide: East_Asian_Width W or F, the file's @missing defaults included (unassigned code points in the
CJK blocks are wide). Emoji with default emoji presentation are W there since Unicode 9.
Zero width: general category Mn, Me and Cf — minus the soft hyphen and the prepended concatenation
marks, which draw.
"""
import re
import sys

OUT = "shared/src/commonMain/kotlin/app/skerry/shared/terminal/UnicodeWidthTables.kt"

# Cf that puts ink on the screen: the soft hyphen (xterm and VTE draw it) and the prepended
# concatenation marks (Arabic number signs and their kin), which carry a glyph of their own.
DRAWN_FORMAT = {0x00AD, 0x0600, 0x0601, 0x0602, 0x0603, 0x0604, 0x0605, 0x06DD, 0x070F,
                0x0890, 0x0891, 0x08E2, 0x110BD, 0x110CD}


def parse(path, keep, missing=False):
    points = set()
    line_re = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)")
    miss_re = re.compile(r"^#\s*@missing:\s*([0-9A-F]+)\.\.([0-9A-F]+)\s*;\s*(\w+)")
    explicit = {}
    defaults = []
    for raw in open(path, encoding="utf-8"):
        m = miss_re.match(raw)
        if m and missing:
            defaults.append((int(m.group(1), 16), int(m.group(2), 16), m.group(3)))
            continue
        m = line_re.match(raw.split("#")[0].strip() if not raw.startswith("#") else "")
        if not m:
            continue
        lo = int(m.group(1), 16)
        hi = int(m.group(2) or m.group(1), 16)
        for cp in range(lo, hi + 1):
            explicit[cp] = m.group(3)
    for lo, hi, value in defaults:
        for cp in range(lo, hi + 1):
            explicit.setdefault(cp, value)
    return {cp for cp, value in explicit.items() if value in keep}


def ranges(points):
    out = []
    for cp in sorted(points):
        if out and out[-1][1] == cp - 1:
            out[-1][1] = cp
        else:
            out.append([cp, cp])
    return out


def kotlin_array(name, doc, rs):
    body = []
    for i in range(0, len(rs), 4):
        body.append("        " + " ".join(f"0x{lo:X}, 0x{hi:X}," for lo, hi in rs[i:i + 4]))
    return f"    /** {doc} */\n    val {name} = intArrayOf(\n" + "\n".join(body) + "\n    )\n"


def main():
    eaw, gc, version = sys.argv[1:4]
    wide = parse(eaw, {"W", "F"}, missing=True)
    zero = parse(gc, {"Mn", "Me", "Cf"}) - DRAWN_FORMAT
    text = f"""package app.skerry.shared.terminal

// GENERATED by tools/unicode/gen_width_tables.py from Unicode {version} — do not edit by hand.

/**
 * Column-width tables of Unicode {version}: sorted, inclusive `[start, end]` pairs, searched by
 * [CharMetrics]. Regenerate with the script named above when moving to a newer Unicode version.
 */
internal object UnicodeWidthTables {{
{kotlin_array("WIDE", "East_Asian_Width W or F: two columns.", ranges(wide))}
{kotlin_array("ZERO_WIDTH", "Mn, Me and Cf that draw nothing of their own: joined to the cell before.", ranges(zero))}}}
"""
    open(OUT, "w", encoding="utf-8").write(text)
    print(f"{OUT}: {len(ranges(wide))} wide, {len(ranges(zero))} zero-width ranges")


if __name__ == "__main__":
    main()
