package app.skerry.shared.share

import app.skerry.shared.sync.SyncSession

/** One live shared session on offer to a team; [meta] is sealed under the team key. */
class SharedSessionInfo(
    val shareId: String,
    val hostAccountId: String,
    val meta: ByteArray,
    val startedAt: Long,
    val viewers: Int,
)

/**
 * Network contract for shared terminal sessions — the relay half of Teams. Stateless like
 * [app.skerry.shared.team.TeamClient]: every call takes the [SyncSession], errors are
 * [app.skerry.shared.sync.SyncException].
 *
 * Both socket calls hand a [ShareChannel] to [block] and stay open until it returns (or the socket
 * dies): the caller drives the session, and leaving the block is how sharing stops.
 */
interface SessionShareClient {
    /** Live shared sessions of [teamId] — what the member can join right now. */
    suspend fun listShares(session: SyncSession, teamId: String): List<SharedSessionInfo>

    /**
     * Opens [shareId] as the host and runs [block] with the relay channel. [meta] is the session's
     * label, already sealed under the team key — the server stores it as an opaque blob.
     */
    suspend fun hostShare(
        session: SyncSession,
        teamId: String,
        shareId: String,
        meta: ByteArray,
        block: suspend (ShareChannel) -> Unit,
    )

    /** Joins [shareId] as a viewer and runs [block] with the relay channel. */
    suspend fun joinShare(
        session: SyncSession,
        teamId: String,
        shareId: String,
        block: suspend (ShareChannel) -> Unit,
    )
}

/**
 * Share ids are generated by the host and travel in a URL path, so they are restricted to an
 * alphabet that cannot mean anything else there. Also the check a client applies before trusting a
 * directory entry from the server.
 */
fun isValidShareId(value: String): Boolean =
    value.isNotEmpty() && value.length <= MAX_SHARE_ID_LENGTH &&
        value.all { it in 'a'..'z' || it in '0'..'9' || it == '-' }

/** Mirrors the server's cap on a share id. */
const val MAX_SHARE_ID_LENGTH: Int = 64
